### ISSUE TITLE
What is the purpose of the focusable sr-only utility?

### ISSUE THREAD

**Issue by austinstarin** [punkave/frontend-starter#11]
https://github.com/punkave/frontend-starter/blob/810d5c9e8dcbab927f28aeffe97c1baf840b8b6e/src/sass/utilities/_display.scss#L4

**Comment by bgantick** [comment]
For things like skip-nav links that we want hidden, but still focusable. See https://github.com/punkave/ysrp/blob/58e5fb70a9b6aaaf722a6619bfe7ce847f1183c2/lib/modules/header-widgets/views/widget.html#L6

**Comment by austinstarin** [comment]
So, on focus we kick it into the viewport.... Makes sense.
