### ISSUE TITLE
Linter files

### ISSUE THREAD

**Issue by bgantick** [punkave/frontend-starter#2]
Linter files are currently in the client boilerplate. Should they just live there? Is this going to be a submodule of the client boilerplate? Should they be removed from the client boilerplate?

**Comment by austinstarin** [comment]
I'm thinking they should live here after recent conversations.

**Comment by abea** [comment]
Agreed. Then projects could maintain the state of the linter when they were created.

**Comment by austinstarin** [comment]
I'm not sure if that's what the topic was here @abea, but that's an intersting thought in general.
