### ISSUE TITLE
.o-grid--justify is a misleading name

### ISSUE THREAD

**Issue by austinstarin** [punkave/frontend-starter#30]
https://github.com/punkave/frontend-starter/blob/810d5c9e8dcbab927f28aeffe97c1baf840b8b6e/src/sass/objects/_grid.scss#L10

**Comment by bgantick** [comment]
`.o-grid--even`?

**Comment by austinstarin** [comment]
I think my point for this was that it's not imposing `flex-direction: justify`. I'm cool with `even` i think?

**Comment by bgantick** [comment]
`justify` isn't a valid value for `flex-direction`. Can you clarify?

**Comment by bgantick** [comment]
I think `--justify` kinda makes sense here actually. 

```
Distribute items evenly
The first item is flush with the start,
the last is flush with the end
```

**Comment by austinstarin** [comment]
OK, sorry I'm doing too many things at once. I'll defer to you.

**Comment by abea** [comment]
`split`? I've thought the same thing.

**Comment by bgantick** [comment]
Feel free to reopen/PR if you feel strongly about renaming.
