### ISSUE TITLE
When you add a new scss file Gulp does not track change unless restart

### ISSUE THREAD

**Issue by austinstarin** [punkave/frontend-starter#38]

**Comment by abea** [comment]
Is this not just a Gulp thing? I recall Grunt being the same way.

**Comment by austinstarin** [comment]
Seems solvable, but yes.

**Comment by bgantick** [comment]
I think this is just how gulp works. Closing.

**Comment by austinstarin** [comment]
That's lame.

**Comment by bgantick** [comment]
JK! Found this: https://github.com/sindresorhus/gulp-ruby-sass/issues/11#issuecomment-33660887
