### ISSUE TITLE
Grid gutter creation needs a mixin/map

### ISSUE THREAD

**Issue by austinstarin** [punkave/frontend-starter#9]

**Comment by abea** [comment]
I think we need to be more granular than we are currently. As an example, in a 12 column grid, an 8 column element makes sense to be 100% at "medium" and "small" breakpoints. A 2 column element, on the other hand, probably should not be 100% width at "medium" and maybe shouldn't be wider than 50% _ever_.

TLDR; The system seems a bit crude at the moment by treating treating all column classes the same.

**Comment by austinstarin** [comment]
Yes, see https://github.com/punkave/frontend-starter/issues/12

The hope is to create selectors to handle different break scenarios.

**Comment by austinstarin** [comment]
This ticket is in RE to creating something like https://github.com/punkave/dfmch/blob/develop/src/sass/objects/_grid.scss#L11-L19

**Comment by abea** [comment]
Sorry, I'll move the comment. I actually started there, but wasn't sure that was the right one...

**Comment by austinstarin** [comment]
No worries! Sorry for opening issues and not explaining them thoroughly.
